sudo: false
language: node_js
cache:
  yarn: true
  directories:
  - bower_components
install:
  - yarn install
  - ./node_modules/.bin/bower install
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
  - npm run build
  - npm run test
  - xvfb-run wct
services:
  - docker
before_deploy:
  - docker pull lokalise/lokalise-cli
deploy:
  provider: script
  script: script/travis_deploy
  on:
    branch: master
dist: trusty
addons:
  sauce_connect: true
